spring.application.name=taskflow
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
spring.datasource.username=taskflow_user
spring.datasource.password=taskflow_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true